const USUARIO_LOADING = 'USUARIO_LOADING';
const USUARIO_ERROR = 'USUARIO_ERROR';
const USUARIO_LOGIN = 'USUARIO_LOGIN';
const USUARIO_LOGOUT = 'USUARIO_LOGOUT';

const BALANCE_LOADING = 'BALANCE_LOADING';
const BALANCE_ERROR = 'BALANCE_ERROR';
const BALANCE_OBTENER_DATOS = 'BALANCE_OBTENER_DATOS';
const BALANCE_CAMBIAR_FECHA = 'BALANCE_CAMBIAR_FECHA';
const BALANCE_CAMBIAR_FORMATO_FECHA = 'BALANCE_CAMBIAR_FORMATO_FECHA'

export {USUARIO_ERROR,USUARIO_LOADING,USUARIO_LOGIN,USUARIO_LOGOUT,BALANCE_CAMBIAR_FECHA,BALANCE_OBTENER_DATOS,BALANCE_LOADING,BALANCE_ERROR,BALANCE_CAMBIAR_FORMATO_FECHA}
