const USUARIO_LOADING = 'USUARIO_LOADING';
const USUARIO_ERROR = 'USUARIO_ERROR';
const USUARIO_LOGIN = 'USUARIO_LOGIN';
const USUARIO_LOGOUT = 'USUARIO_LOGOUT';
const USUARIO_SESION_VENCIDA = 'USUARIO_SESION_VENCIDA';

const BALANCE_LOADING = 'BALANCE_LOADING';
const BALANCE_ERROR = 'BALANCE_ERROR';
const BALANCE_OBTENER_DATOS = 'BALANCE_OBTENER_DATOS';
const BALANCE_CAMBIAR_FECHA = 'BALANCE_CAMBIAR_FECHA';
const BALANCE_CAMBIAR_FORMATO_FECHA = 'BALANCE_CAMBIAR_FORMATO_FECHA'

const VENTAS_LOADING = 'VENTAS_LOADING';
const VENTAS_ERROR = 'VENTAS_ERROR';
const VENTAS_OBTENER_ULTIMAS = 'VENTAS_OBTENER_ULTIMAS';

const MEDIOS_DE_PAGO_LOADING = 'MEDIOS_DE_PAGO_LOADING';
const MEDIOS_DE_PAGO_ERROR = 'MEDIOS_DE_PAGO_ERROR';
const MEDIOS_DE_PAGO_OBTENER_INFORME = 'MEDIOS_DE_PAGO_OBTENER_INFORME';

const MARCAS_LOADING = 'MARCAS_LOADING';
const MARCAS_ERROR = 'MARCAS_ERROR';
const MARCAS_TRAER_TODAS = 'MARCAS_TRAER_TODAS';
const MARCAS_APLICAR_AUMENTO = 'MARCAS_APLICAR_AUMENTO';

const OFERTAS_LOADING = 'OFERTAS_LOADING';
const OFERTAS_ERROR = 'OFERTAS_ERROR';
const OFERTAS_TRAER = 'OFERTAS_TRAER';
const OFERTAS_TRAER_MAS = 'OFERTAS_TRAER_MAS';
const OFERTAS_UPDATE_PAGINATION = 'OFERTAS_UPDATE_PAGINATION';
const OFERTAS_AGREGAR = 'OFERTAS_AGREGAR';
const OFERTAS_MODIFICAR = 'OFERTAS_MODIFICAR';
const OFERTAS_TRAER_UNA = 'OFERTAS_TRAER_UNA';
const OFERTAS_AGREGAR_PRODUCTO = 'OFERTAS_AGREGAR_PRODUCTO';
const OFERTAS_ELIMINAR_PRODUCTO = 'OFERTAS_ELIMINAR_PRODUCTO';
const OFERTAS_ELIMINAR = 'OFERTAS_ELIMINAR';


export {USUARIO_ERROR,USUARIO_LOADING,USUARIO_LOGIN,USUARIO_LOGOUT,USUARIO_SESION_VENCIDA,BALANCE_CAMBIAR_FECHA,BALANCE_OBTENER_DATOS,BALANCE_LOADING,BALANCE_ERROR,BALANCE_CAMBIAR_FORMATO_FECHA,VENTAS_ERROR,VENTAS_OBTENER_ULTIMAS,VENTAS_LOADING,MEDIOS_DE_PAGO_ERROR,MEDIOS_DE_PAGO_LOADING,MEDIOS_DE_PAGO_OBTENER_INFORME,MARCAS_ERROR,MARCAS_LOADING,MARCAS_TRAER_TODAS,MARCAS_APLICAR_AUMENTO,OFERTAS_LOADING,OFERTAS_ERROR,OFERTAS_TRAER,OFERTAS_TRAER_MAS,OFERTAS_UPDATE_PAGINATION,OFERTAS_AGREGAR,OFERTAS_MODIFICAR,OFERTAS_TRAER_UNA,OFERTAS_AGREGAR_PRODUCTO,OFERTAS_ELIMINAR_PRODUCTO,OFERTAS_ELIMINAR}
